/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts,scss}",
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-hover': 'var(--bg-hover)',
        'bg-active': 'var(--bg-active)',
        primary: 'var(--primary)',
        'primary-light': 'var(--primary-light)',
        'primary-dark': 'var(--primary-dark)',
        secondary: 'var(--secondary)',
        'secondary-light': 'var(--secondary-light)',
        'secondary-dark': 'var(--secondary-dark)',
        accent: 'var(--accent)',
        'accent-light': 'var(--accent-light)',
        'accent-dark': 'var(--accent-dark)',
        text: 'var(--text)',
        'text-muted': 'var(--text-muted)',
        'text-dim': 'var(--text-dim)',
        'text-inverse': 'var(--text-inverse)',
        success: 'var(--success)',
        'success-light': 'var(--success-light)',
        'success-bg': 'var(--success-bg)',
        'success-border': 'var(--success-border)',
        error: 'var(--error)',
        'error-light': 'var(--error-light)',
        'error-bg': 'var(--error-bg)',
        'error-border': 'var(--error-border)',
        warning: 'var(--warning)',
        'warning-light': 'var(--warning-light)',
        'warning-bg': 'var(--warning-bg)',
        'warning-border': 'var(--warning-border)',
        card: 'var(--card)',
        'card-border': 'var(--card-border)',
        line: 'var(--line)',
        'line-light': 'var(--line-light)',
        'table-bg': 'var(--table-bg)',
        'table-header': 'var(--table-header-bg)',
        'table-stripe': 'var(--table-stripe)',
        'input-bg': 'var(--input-bg)',
        'input-border': 'var(--input-border)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
        'sm': 'var(--radius-sm)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
      },
      boxShadow: {
        DEFAULT: 'var(--shadow)',
        'lg': 'var(--shadow-lg)',
        'sm': 'var(--shadow-sm)',
      },
      transitionDuration: {
        'fast': 'var(--transition-fast)',
        'DEFAULT': 'var(--transition)',
        'slow': 'var(--transition-slow)',
      },
      animation: {
        shimmer: 'shimmer 1.8s ease-in-out infinite',
        spin: 'spin 1.5s linear infinite',
        pulse: 'pulse 2s ease-in-out infinite',
        fadeIn: 'fadeIn 0.3s ease',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        fadeIn: {
          'from': { opacity: '0' },
          'to': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
